config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :users do
    member do
      get :activate
      patch :post_create
    end
  end

  get '/sign_up', to: 'users#new', as: :signup

  resources :sessions
  get '/login', to: 'sessions#new', as: :login
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :reset_passwords, only: %i[new create update edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  private

  def not_authenticated
    flash[:warning] = 'You have to authenticate to access this page.'
    redirect_to login_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  skip_before_action :require_login

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      @user.deliver_reset_password_instructions!
      flash[:success] = "Instructions have been sent to your email.  #{edit_reset_password_url(id: @user.reset_password_token)}"
      redirect_to login_path
    else
      flash[:warning] = "Account with such email doesn't exist"
    end
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated if @user.blank?
  end

  def update
    @user = User::ResetPassword.(params[:user].merge(id: params[:id]))
    if @user.success?
      flash[:success] = 'Successfuly updated!'
      redirect_to login_path
    else
      flash[:warning] = "#{@user['contract.default'].errors.messages}"
      redirect_to edit_reset_password_path(id: params[:id])
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def create
    if login(params[:email], params[:password], params[:remember_me])
      flash[:success] = 'Welcome back!'
      redirect_to users_path
    else
      user = User.find_by(email: params[:email])
      if user.present? && user.activation_state == 'pending'
          flash.now[:warning] = 'Your account is not actived'
      else
        flash.now[:warning] = 'E-mail and/or password is incorrect.'
      end
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = 'See you!'
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create activate post_create]
  before_action :set_user, only: %i[edit show]

  def index
    @users = User.all #zaglushka chto bi chto-to pokazivat'
  end

  def new
    @user = User.new
  end

  def create
    @user = User::PreCreate.(params[:user])
    if @user.success?
      flash[:success] = "Welcome!  #{activate_user_url(@user['model'].activation_token)}"
      redirect_to login_path
    else
      render 'new'
    end
  end

  def update
    @user = User::Update.(params[:user].merge(id: params[:id]))
    if @user.success?
      flash[:success] = 'Successfuly updated!'
      redirect_to users_path
    else
      flash[:warning] = "#{@user['contract.default'].errors.messages}"
      redirect_to edit_user_path
    end
  end

  def activate
    @user = User.load_from_activation_token(params[:id])
  end

  def post_create
    @user = User::Activate.new.(params[:user].merge(id: params[:id]))
    if @user.success?
      flash[:success] = 'HERE WE GO BABY!'
      redirect_to login_path
    else
      flash[:warning] = "wtf! #{@user['contract.default'].errors.messages}"
      redirect_to activate_user_url
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stisn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <% if current_user %>
    <%= current_user.email %>
    <%= link_to 'Log Out', logout_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign Up', signup_path %>
    <%= link_to 'Log In', login_path %>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/main/home.slim
.home-page1
  .container
    .row
      .sign
        h1.text-center.title Social Networks Auto Poster
        .col-md-3.col-md-offset-3
          = link_to 'Sign In', '', class: "btn btn-lg btn-block sign-in"
        .col-md-3
          = link_to 'Sign Up', '', class: "btn btn-lg btn-block sign-up"
.home-page2
  .container

    .row
      .col-md-12
        .sign-description
          h2.text-center.description Shedule posts for social networks with ease!
          h5.text-centr.description We provide easy and understandable management of deferred social networks.<br>Delayed run, best time to publicaion, minimalistic and flexible configuration.<br>Leave your email and we are contact you when we are ready to start.<br>Start with us and be one of the first users!

        form.form-inline.text-center
          .form-group
            = email_field_tag 'email', '', class: 'input-lg form-control'
          = submit_tag 'Subscrible', class: 'btn btn-lg subscrible'

  .footer 

app/views/reset_passwords/edit.html.haml
%h1 Choose a new password

= form_for @user, url: reset_password_path(@token), method: :patch do |f|
  %div
    = f.label :password
    = f.password_field :password, required: true
  %div
    = f.label :password_confirmation
    = f.password_field :password_confirmation, required: true
  %div
    = f.submit 'Set password'

app/views/reset_passwords/new.html.haml
%h1 Reset password

= form_tag reset_passwords_path, method: :post do
  %div
    = label_tag :email
    = text_field_tag :email, nil, required: true

  %div
    = submit_tag 'Reset password'

app/views/users/_form.html.haml
= simple_form_for User.new do |f|
  %div
    = f.label :email
    = f.email_field :email
  %div
    = f.submit 'Register'

app/views/users/_user.html.erb
<h3><%= link_to user.email, user_path(user) %> </h3>

<div>
  <%= link_to 'Change', edit_user_path(user) %> |
  <%= link_to 'Delete', user, method: :delete, data: {confirm: 'Are you sure?'}%>
</div>

app/views/users/activate.html.haml
= simple_form_for @user, url: post_create_user_path do |f|
  %div
    = f.label :email
    = f.email_field :email
  %div
    = f.label :password
    = f.password_field :password
  %div
    = f.label :password_confirmation, virtual: true
    = f.password_field :password_confirmation, virtual: true
  %div
    = f.submit 'End up registration'

app/views/users/edit.html.haml
%h2 Edit

= simple_form_for @user do |f|
  %div
    = f.label :email
    = f.email_field :email
  %div
    = f.label :old_password
    = f.password_field :old_password, virtual: true
  %div
    = f.label :password
    = f.password_field :password
  %div
    = f.label :password_confirmation
    = f.password_field :password_confirmation, virtual: true
  %div
    = f.submit 'Edit'
  %div
    = link_to 'Back', :back

app/views/users/index.html.erb
<h2> users: </h2>

<%= render @users %>


<div>
  <%= link_to 'New user', new_user_path %>
</div>

app/views/users/new.html.haml
%p#notice= notice

%h1 Registration

= render 'form'

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong email:
  = @user.email
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path